### ISSUE TITLE
[PE-D][Tester C] Unclear specification of the t/ field in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-2/tp#163]
Sometimes **t/@telegramName** is used in the UG and other times **t/telegramName** is used. 
Inconsistency in specifying exactly which is accepted or if both is accepted.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: jingting1412/ped#4

**Comment by flexibo** [comment]
Duplicate of 
- #159
