### ISSUE TITLE
[PE-D][Tester E] Inaccurate error message for a long phone number input that seems valid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W09-2/tp#180]
This input below 

`add n/John Doe p/9876543233333333333333333333333333333333333333333333333333333333333333 e/johnd@example.com a/311, Clementi Ave 2, #02-25 c/Apple t/@johndoe`

results in this output message

![image.png](https://raw.githubusercontent.com/sp4ce-cowboy/ped/main/files/7e071bc0-3610-4c66-a39b-e988434b5f35.png)

even though the input only contains numbers and is longer than 5 digits. In the user guide, it is only not clear if there is an upper limit to the phone number digits that can be input.

![image.png](https://raw.githubusercontent.com/sp4ce-cowboy/ped/main/files/be5c26b5-d6a4-485a-ac0e-cee1c90a74b5.png)

However, given that it is unlikely for someone to have such a long phone number, this is a low severity bug. It would be better if the error message was more specific to the case, such as a `number too long` warning.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: sp4ce-cowboy/ped#3

**Comment by sushiyade** [comment]
Please refer to issue #224,
Thank you!
