### ISSUE TITLE
[PE-D][Tester E] Duplicated name matches when finding for a name that is different based on case-sensitivity

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W09-2/tp#192]
The command `filter-n` is supposed to be case insensitive. However, the input `filter-n n/John` results in this output:

![image.png](https://raw.githubusercontent.com/sp4ce-cowboy/ped/main/files/1edc4f66-2ddd-4835-bb2f-6f2d6d9ff183.png)

Following from a previous issue about duplicate names being allowed, this would mean that it is not possible to find a singular and specific person based on the case sensitivity in their name. If both `John Doe` and `john doe` are valid contacts, it would not be possible to search for a specific person using the `filter-n` command. There is a mismatch between contact names that are allowed and contact names that can be searched. 

However, this does not impeded functionality severely so it is a very low severity bug.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: sp4ce-cowboy/ped#5

**Comment by flexibo** [comment]
Fix by explicitly saying that only filter-n and filter-c commands are case insensitive for contacts tab
