### ISSUE TITLE
[PE-D][Tester B] Contacts Management section of UG has incorrect command description

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W09-2/tp#213]
For the following part in the Contacts Management section of the UG: "Clearing all entries : Contacts Tab → `clear`", the description is stated wrongly.

Expected: `Clears all entries from the Contacts Tab.`

Actual: `Clears all entries from the Finance Tab.`

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: aslam341/ped#14

**Comment by flexibo** [comment]
Duplicate issue:
- #169
